# configure isort to be compatible with black
# source: https://black.readthedocs.io/en/stable/compatible_configs.html#configuration
[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.black]
# flake8 settings prefer single strings:
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.venv
  | dist
)/
'''

[flake8]
max-line-length = 89
max-complexity = 18
