version: 2

sources:
  - name: s3
    tables:
      - name: raw_customers
        external:
          url: "{{ env_var('SECURE_BUCKET_PATH') }}"
          object_pattern: '*raw_customers.csv'
          credentials:
            aws_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
            aws_secret_key: "{{ env_var('AWS_ACCESS_SECRET_KEY') }}"
          type: '(CSV SKIP_HEADER_ROWS=true)'
        columns:
          - name: id
            data_type: int
          - name: first_name
            data_type: TEXT
          - name: last_name
            data_type: TEXT
