name: Python code checks

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Hack to temporary fix mypy errors
        # TODO: remove once compatible with dbt-core==1.3.0
        pip install "dbt-core<1.3.0"
        pip install ".[dev]"

    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.3
