name: Python code checks

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # pip 24.2 has issues installing the Logbook dependency
        python -m pip install --upgrade "pip<=24.1.2"
        python -m pip install ".[dev]"

    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.3
