name: Run Jaffle shop tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_USERNAME:
        required: true
      FIREBOLT_PASSWORD:
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dbt-adapter code
        uses: actions/checkout@v2
        with:
          path: dbt-firebolt

      - name: Check out Jaffle Shop code
        uses: actions/checkout@v2
        with:
          repository: firebolt-db/jaffle_shop_firebolt
          path: jaffle-shop
          
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-firebolt/.[dev]"

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@master
        with:
          firebolt-username: ${{ secrets.FIREBOLT_USERNAME }}
          firebolt-password: ${{ secrets.FIREBOLT_PASSWORD }}
          api-endpoint: "api.dev.firebolt.io"
          region: "us-east-1"

      - name: Run Jaffle Shop test workflow
        env:
          USER_NAME: ${{ secrets.FIREBOLT_USERNAME }}
          PASSWORD: ${{ secrets.FIREBOLT_PASSWORD }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          API_ENDPOINT: "api.dev.firebolt.io"
          ACCOUNT_NAME: "firebolt"
          DBT_PROFILES_DIR: "../dbt-firebolt/.github/workflows/jaffle_shop"
        working-directory: jaffle-shop
        run:
          ../dbt-firebolt/.github/workflows/jaffle_shop/run_test_workflow.sh
          
        
