name: Run Jaffle shop tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - staging
  workflow_call:
    inputs:
      environment:
        default: 'staging'
        required: false
        type: string
    secrets:
      FIREBOLT_USERNAME:
        required: true
      FIREBOLT_PASSWORD:
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dbt-adapter code
        uses: actions/checkout@v2
        with:
          path: dbt-firebolt

      - name: Check out Jaffle Shop code
        uses: actions/checkout@v2
        with:
          repository: firebolt-db/jaffle_shop_firebolt
          path: jaffle-shop
          
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-firebolt/.[dev]"

      - name: Determine env variables
        run: |
          if [ "${{ inputs.environment }}" == 'staging' ]; then
             echo "USERNAME=${{ secrets.FIREBOLT_USERNAME_STAGING }}" >> "$GITHUB_ENV"
             echo "PASSWORD=${{ secrets.FIREBOLT_PASSWORD_STAGING }}" >> "$GITHUB_ENV"
          else
             echo "USERNAME=${{ secrets.FIREBOLT_USERNAME_DEV }}" >> "$GITHUB_ENV"
             echo "PASSWORD=${{ secrets.FIREBOLT_PASSWORD_DEV }}" >> "$GITHUB_ENV"
          fi

      - name: Keep environment name in the summary
        run: echo '### Ran integration tests against ${{ inputs.environment }} ' >> $GITHUB_STEP_SUMMARY

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@master
        with:
          firebolt-username: ${{ env.USERNAME }}
          firebolt-password: ${{ env.PASSWORD }}
          api-endpoint: "api.${{ inputs.environment }}.firebolt.io"
          region: "us-east-1"

      - name: Run Jaffle Shop test workflow
        env:
          USER_NAME: ${{ env.USERNAME }}
          PASSWORD: ${{ env.PASSWORD }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          API_ENDPOINT: "api.${{ inputs.environment }}.firebolt.io"
          ACCOUNT_NAME: "firebolt"
          DBT_PROFILES_DIR: "../dbt-firebolt/.github/workflows/jaffle_shop"
        working-directory: jaffle-shop
        run:
          ../dbt-firebolt/.github/workflows/jaffle_shop/run_test_workflow.sh
          
        
