name: Run Jaffle shop tests V1
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_STG_USERNAME:
        required: true
      FIREBOLT_STG_PASSWORD:
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dbt-adapter code
        uses: actions/checkout@v2
        with:
          path: dbt-firebolt

      - name: Check out Jaffle Shop code
        uses: actions/checkout@v2
        with:
          repository: firebolt-db/jaffle_shop_firebolt
          path: jaffle-shop

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "dbt-firebolt/.[dev]"

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@v1
        with:
          firebolt-username: ${{ secrets.FIREBOLT_STG_USERNAME }}
          firebolt-password: ${{ secrets.FIREBOLT_STG_PASSWORD }}
          api-endpoint: "api.staging.firebolt.io"
          region: "us-east-1"

      - name: Run Jaffle Shop test workflow
        env:
          USER_NAME: ${{ secrets.FIREBOLT_STG_USERNAME }}
          PASSWORD: ${{ secrets.FIREBOLT_STG_PASSWORD }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          API_ENDPOINT: "api.staging.firebolt.io"
          ACCOUNT_NAME: "firebolt"
          DBT_PROFILES_DIR: "../dbt-firebolt/.github/workflows/jaffle_shop"
          SECURE_BUCKET_PATH: ${{ vars.SECURE_BUCKET_PATH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        working-directory: jaffle-shop
        run:
          ../dbt-firebolt/.github/workflows/jaffle_shop/run_test_workflow.sh
