name: Run Jaffle shop tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_USERNAME_STAGING:
        required: true
      FIREBOLT_PASSWORD_STAGING:
        required: true
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
jobs:
  jaffle-shop-v1:
    uses: ./.github/workflows/jaffle-shop-v1.yml
    secrets: inherit
  jaffle-shop-v2:
    uses: ./.github/workflows/jaffle-shop-v2.yml
    secrets: inherit
