name: Run Jaffle shop tests V2
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out dbt-adapter code
        uses: actions/checkout@v2
        with:
          path: dbt-firebolt

      - name: Check out Jaffle Shop code
        uses: actions/checkout@v2
        with:
          repository: firebolt-db/jaffle_shop_firebolt
          path: jaffle-shop

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd dbt-firebolt
          python -m pip install dbt-core -e .

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@v2
        with:
          firebolt-client-id: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
          firebolt-client-secret: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
          account: ${{ vars.FIREBOLT_ACCOUNT }}
          api-endpoint: "api.staging.firebolt.io"

      - name: Run Jaffle Shop test workflow
        env:
          USER_NAME: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
          PASSWORD: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          API_ENDPOINT: "api.staging.firebolt.io"
          ACCOUNT_NAME: ${{ vars.FIREBOLT_ACCOUNT }}
          SECURE_BUCKET_PATH: ${{ vars.SECURE_BUCKET_PATH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          AWS_ACCESS_ROLE_ARN: ${{ secrets.AWS_ACCESS_ROLE_ARN }}
          DBT_PROFILES_DIR: "../dbt-firebolt/.github/workflows/jaffle_shop"
        working-directory: jaffle-shop
        run: |
          ../dbt-firebolt/.github/workflows/jaffle_shop/run_test_workflow.sh
