name: Nightly code check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # 3 am UTC every day
jobs:
  code-check:
    uses: ./.github/workflows/code-check.yml
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # finish all jobs even if one fails
      max-parallel: 2
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Check out dbt-adapter code
        uses: actions/checkout@v4
        with:
          path: dbt-firebolt

      - name: Check out Jaffle Shop code
        uses: actions/checkout@v4
        with:
          repository: firebolt-db/jaffle_shop_firebolt
          path: jaffle-shop

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          # pip 24.2 has issues installing the Logbook dependency
          python -m pip install --upgrade "pip<=24.1.2"
          pip install -e "dbt-firebolt/.[dev]"

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@v2
        with:
          firebolt-client-id: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
          firebolt-client-secret: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
          account: ${{ vars.FIREBOLT_ACCOUNT }}
          api-endpoint: "api.staging.firebolt.io"

      - name: Run Jaffle Shop test workflow
        env:
          USER_NAME: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
          PASSWORD: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          API_ENDPOINT: "api.staging.firebolt.io"
          ACCOUNT_NAME: ${{ vars.FIREBOLT_ACCOUNT }}
          DBT_PROFILES_DIR: "../dbt-firebolt/.github/workflows/jaffle_shop"
          SECURE_BUCKET_PATH: ${{ vars.SECURE_BUCKET_PATH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          AWS_ACCESS_ROLE_ARN: ${{ secrets.AWS_ACCESS_ROLE_ARN }}
        working-directory: jaffle-shop
        shell: bash
        run: |
          ../dbt-firebolt/.github/workflows/jaffle_shop/run_test_workflow.sh

      - name: Slack Notify of failure
        if: failure()
        id: slack
        uses: firebolt-db/action-slack-nightly-notify@v1
        with:
          os: ${{ matrix.os }}
          programming-language: Python
          language-version: ${{ matrix.python-version }}
          notifications-channel: 'ecosystem-ci-notifications'
          slack-api-key: ${{ secrets.SLACK_BOT_TOKEN }}
