name: Firebolt Python Release

on:
  workflow_dispatch:
    inputs:
      pre-release-tag:
        required: false
        description: 'Tag for pre-release (optional)'
      major-release:
        required: false
        description: 'Trigger a major release (optional). Leave empty for regular release.'

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    secrets:
      FIREBOLT_USERNAME: ${{ secrets.FIREBOLT_USERNAME }}
      FIREBOLT_PASSWORD: ${{ secrets.FIREBOLT_PASSWORD }}

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: integration-tests
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_PAT }}

    - name: 'Publish action'
      uses: firebolt-db/action-python-release@main
      with:
        pre-release-tag: ${{ inputs.pre-release-tag }}
        major-release: ${{ inputs.major-release }}
        pypi-username: ${{ secrets.PYPI_USERNAME }}
        pypi-password: ${{ secrets.PYPI_PASSWORD }}
        version-file-path: dbt/adapters/firebolt/__init__.py
