name: Firebolt Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Hack version attr for security scanning"
        run: |
          cp dbt/adapters/firebolt/__init__.py dbt/
          sed -i 's#attr: dbt.adapters.firebolt.__version__#attr: dbt.__version__#' setup.cfg
          
      - name: "Security Scan"
        run: |
          python3 -V
          python3 -m pip install pipenv
          python3 -m pipenv --version
          python3 -m pipenv install -e "."

