name: Firebolt Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Security Scan"
        run: |
          python3 -V
          python3 -m pipenv --version
          python3 -m pipenv install -e "."
